# -*- mode: python ; coding: utf-8 -*-

import os

# Collect all .py files from core/ and ui/ packages
block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'core',
        'core.apdu',
        'core.atr_parser',
        'core.desfire',
        'core.diversification',
        'core.javacard',
        'core.legic',
        'core.reader_manager',
        'ui',
        'ui.app',
        'ui.apdu_console',
        'ui.card_info_view',
        'ui.desfire_view',
        'ui.diversification_view',
        'ui.javacard_view',
        'ui.legic_view',
        'ui.log_panel',
        'ui.reader_panel',
        'ui.theme',
        'customtkinter',
        'PIL',
        'smartcard',
        'smartcard.System',
        'smartcard.CardConnection',
        'smartcard.CardMonitoring',
        'smartcard.ReaderMonitoring',
        'smartcard.Exceptions',
        'smartcard.pcsc',
        'smartcard.pcsc.PCSCReader',
        'smartcard.pcsc.PCSCContext',
        'smartcard.pcsc.PCSCCardConnection',
        'smartcard.scard',
        'Crypto',
        'Crypto.Cipher',
        'Crypto.Cipher.AES',
        'Crypto.Cipher.DES',
        'Crypto.Cipher.DES3',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SmartCardReader',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='NONE',
)
